/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthTodayImport } from './routes/_auth.today'
import { Route as AuthTimeEstimateImport } from './routes/_auth.time-estimate'
import { Route as AuthCalendarImport } from './routes/_auth.calendar'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthTodayRoute = AuthTodayImport.update({
  path: '/today',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTimeEstimateRoute = AuthTimeEstimateImport.update({
  path: '/time-estimate',
  getParentRoute: () => AuthRoute,
} as any)

const AuthCalendarRoute = AuthCalendarImport.update({
  path: '/calendar',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/calendar': {
      id: '/_auth/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthCalendarImport
      parentRoute: typeof AuthImport
    }
    '/_auth/time-estimate': {
      id: '/_auth/time-estimate'
      path: '/time-estimate'
      fullPath: '/time-estimate'
      preLoaderRoute: typeof AuthTimeEstimateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/today': {
      id: '/_auth/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthTodayImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthCalendarRoute: typeof AuthCalendarRoute
  AuthTimeEstimateRoute: typeof AuthTimeEstimateRoute
  AuthTodayRoute: typeof AuthTodayRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCalendarRoute: AuthCalendarRoute,
  AuthTimeEstimateRoute: AuthTimeEstimateRoute,
  AuthTodayRoute: AuthTodayRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof AboutLazyRoute
  '/calendar': typeof AuthCalendarRoute
  '/time-estimate': typeof AuthTimeEstimateRoute
  '/today': typeof AuthTodayRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof AboutLazyRoute
  '/calendar': typeof AuthCalendarRoute
  '/time-estimate': typeof AuthTimeEstimateRoute
  '/today': typeof AuthTodayRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof AboutLazyRoute
  '/_auth/calendar': typeof AuthCalendarRoute
  '/_auth/time-estimate': typeof AuthTimeEstimateRoute
  '/_auth/today': typeof AuthTodayRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/about'
    | '/calendar'
    | '/time-estimate'
    | '/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/about'
    | '/calendar'
    | '/time-estimate'
    | '/today'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/about'
    | '/_auth/calendar'
    | '/_auth/time-estimate'
    | '/_auth/today'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AboutLazyRoute: typeof AboutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AboutLazyRoute: AboutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login",
        "/register",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/calendar",
        "/_auth/time-estimate",
        "/_auth/today"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_auth/calendar": {
      "filePath": "_auth.calendar.tsx",
      "parent": "/_auth"
    },
    "/_auth/time-estimate": {
      "filePath": "_auth.time-estimate.tsx",
      "parent": "/_auth"
    },
    "/_auth/today": {
      "filePath": "_auth.today.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
